### ISSUE TITLE
{"code": 20003, "detail": "Your AccountSid or AuthToken was incorrect.", "message": "Authentication Error - No credentials provided", "more_info": "https://www.twilio.com/docs/errors/20003", "status": 401}

### ISSUE THREAD

**Issue by twilio-akiramoto** [stevinoverholser/Preference_Center#2]
Hello,
I am getting this error:
{"code": 20003, "detail": "Your AccountSid or AuthToken was incorrect.", "message": "Authentication Error - No credentials provided", "more_info": "https://www.twilio.com/docs/errors/20003", "status": 401}

I dont see any logs on Studio.
When testing using Curl, same AcctSID and Auth Token, it works.

response3 = HTTParty.post("https://studio.twilio.com/v1/Flows/FWbXX/Executions", body: {To: "+XX", From: "+XX", Parameters: parameters})
puts response3 

I tried this without success:

response3 = HTTParty.post("https://studio.twilio.com/v1/Flows/FWbXX/Executions", :headers => {
   "Authorization" => "Basic AC6XX:aXX"}" 

What is the correct way to authenticate the Studio call?

Thanks,

Al

**Comment by stevinoverholser** [comment]
Hello Al!

HTTParty will want you to pass the basic auth in the URL param:

`response3 = HTTParty.post("https://{AcctSID}:{AuthToken}@studio.twilio.com/v1/Flows/FWXX/Executions", body: {To: "+19706312302", From: "+17205730108", Parameters: parameters})
`

Where you replace **{AcctSID}:{AuthToken}** 

Let me know if this works for you.

**Comment by twilio-akiramoto** [comment]
It worked ! Thank you!
